[platformio]
default_envs = esp32c5_n8r8
boards_dir = boards

[env:esp32c5_n8r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c5-n8r8
framework = arduino
monitor_speed = 115200
upload_speed = 460800

board_build.flash_mode = qio
board_build.flash_size = 8MB
board_build.arduino.memory_type = qio_qspi
board_build.psram_type = qio
board_build.partitions = default_8MB.csv

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MISO=2
    -DTFT_MOSI=7
    -DTFT_SCLK=6
    -DTFT_CS=10
    -DTFT_DC=14
    -DTFT_RST=-1
    -DTFT_RGB_ORDER=TFT_BGR
    -DSPI_FREQUENCY=40000000
    -DSPI_READ_FREQUENCY=16000000
    -DLOAD_GLCD=1
    -DUSE_FSPI_PORT=1

extra_scripts =
    pre:scripts/patch_tft_espi_c5.py

lib_deps =
    bodmer/TFT_eSPI @ 2.5.43
